<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Dates and times: lubridate | R Data Science Book</title>
  <meta name="description" content="4 Dates and times: lubridate | R Data Science Book" />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Dates and times: lubridate | R Data Science Book" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="tillschwoerer/R-data-science-book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Dates and times: lubridate | R Data Science Book" />
  
  
  

<meta name="author" content="Tools and Programming Languages for Data Scientists, FH Kiel, Summer Term 2020" />


<meta name="date" content="2020-05-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="dplyr.html"/>
<link rel="next" href="forcats.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#goals"><i class="fa fa-check"></i><b>1.1</b> Goals</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#data"><i class="fa fa-check"></i><b>1.2</b> Data</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#git-and-github"><i class="fa fa-check"></i><b>1.3</b> Git and GitHub</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="tidyr.html"><a href="tidyr.html"><i class="fa fa-check"></i><b>2</b> Tidying data: tidyr</a></li>
<li class="chapter" data-level="3" data-path="dplyr.html"><a href="dplyr.html"><i class="fa fa-check"></i><b>3</b> Wrangling data: dplyr</a><ul>
<li class="chapter" data-level="3.1" data-path="dplyr.html"><a href="dplyr.html#typical-workflows"><i class="fa fa-check"></i><b>3.1</b> Two typial workflows</a></li>
<li class="chapter" data-level="3.2" data-path="dplyr.html"><a href="dplyr.html#manipulating-rows"><i class="fa fa-check"></i><b>3.2</b> Manipulating rows</a><ul>
<li class="chapter" data-level="3.2.1" data-path="dplyr.html"><a href="dplyr.html#extract-rows"><i class="fa fa-check"></i><b>3.2.1</b> Extract rows</a></li>
<li class="chapter" data-level="3.2.2" data-path="dplyr.html"><a href="dplyr.html#arranging-rows"><i class="fa fa-check"></i><b>3.2.2</b> Arranging rows</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="dplyr.html"><a href="dplyr.html#manipulating-columns"><i class="fa fa-check"></i><b>3.3</b> Manipulating columns</a><ul>
<li class="chapter" data-level="3.3.1" data-path="dplyr.html"><a href="dplyr.html#extract-and-rename-columns"><i class="fa fa-check"></i><b>3.3.1</b> Extract and rename columns</a></li>
<li class="chapter" data-level="3.3.2" data-path="dplyr.html"><a href="dplyr.html#create-new-columns"><i class="fa fa-check"></i><b>3.3.2</b> Create new columns</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="dplyr.html"><a href="dplyr.html#scoped-functions"><i class="fa fa-check"></i><b>3.4</b> Scoped functions</a></li>
<li class="chapter" data-level="3.5" data-path="dplyr.html"><a href="dplyr.html#summarise"><i class="fa fa-check"></i><b>3.5</b> Summarise</a></li>
<li class="chapter" data-level="3.6" data-path="dplyr.html"><a href="dplyr.html#combining-tables"><i class="fa fa-check"></i><b>3.6</b> Combining tables</a></li>
<li class="chapter" data-level="3.7" data-path="dplyr.html"><a href="dplyr.html#database-backend"><i class="fa fa-check"></i><b>3.7</b> Database backend</a><ul>
<li class="chapter" data-level="3.7.1" data-path="dplyr.html"><a href="dplyr.html#motivation"><i class="fa fa-check"></i><b>3.7.1</b> Motivation</a></li>
<li class="chapter" data-level="3.7.2" data-path="dplyr.html"><a href="dplyr.html#set-up"><i class="fa fa-check"></i><b>3.7.2</b> Set up</a></li>
<li class="chapter" data-level="3.7.3" data-path="dplyr.html"><a href="dplyr.html#querying-the-database"><i class="fa fa-check"></i><b>3.7.3</b> Querying the database</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="lubridate.html"><a href="lubridate.html"><i class="fa fa-check"></i><b>4</b> Dates and times: lubridate</a><ul>
<li class="chapter" data-level="4.1" data-path="lubridate.html"><a href="lubridate.html#what-is-lubridate"><i class="fa fa-check"></i><b>4.1</b> What is Lubridate?</a></li>
<li class="chapter" data-level="4.2" data-path="lubridate.html"><a href="lubridate.html#basics"><i class="fa fa-check"></i><b>4.2</b> Basics</a></li>
<li class="chapter" data-level="4.3" data-path="lubridate.html"><a href="lubridate.html#import-data-clean-date-time"><i class="fa fa-check"></i><b>4.3</b> Import data, clean date-time</a></li>
<li class="chapter" data-level="4.4" data-path="lubridate.html"><a href="lubridate.html#check-and-modify-data"><i class="fa fa-check"></i><b>4.4</b> Check and modify data</a></li>
<li class="chapter" data-level="4.5" data-path="lubridate.html"><a href="lubridate.html#before-exploration"><i class="fa fa-check"></i><b>4.5</b> Before exploration</a><ul>
<li class="chapter" data-level="4.5.1" data-path="lubridate.html"><a href="lubridate.html#intervals"><i class="fa fa-check"></i><b>4.5.1</b> Intervals</a></li>
<li class="chapter" data-level="4.5.2" data-path="lubridate.html"><a href="lubridate.html#groupings"><i class="fa fa-check"></i><b>4.5.2</b> Groupings</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="lubridate.html"><a href="lubridate.html#exploration---analysis"><i class="fa fa-check"></i><b>4.6</b> Exploration - Analysis</a><ul>
<li class="chapter" data-level="4.6.1" data-path="lubridate.html"><a href="lubridate.html#temperatur"><i class="fa fa-check"></i><b>4.6.1</b> Temperatur</a></li>
<li class="chapter" data-level="4.6.2" data-path="lubridate.html"><a href="lubridate.html#rainfall"><i class="fa fa-check"></i><b>4.6.2</b> Rainfall</a></li>
<li class="chapter" data-level="4.6.3" data-path="lubridate.html"><a href="lubridate.html#humidity"><i class="fa fa-check"></i><b>4.6.3</b> Humidity</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="lubridate.html"><a href="lubridate.html#wrap-up"><i class="fa fa-check"></i><b>4.7</b> Wrap up</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="forcats.html"><a href="forcats.html"><i class="fa fa-check"></i><b>5</b> Categorical data: forcats</a><ul>
<li class="chapter" data-level="5.1" data-path="forcats.html"><a href="forcats.html#introduction"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="forcats.html"><a href="forcats.html#general-functions"><i class="fa fa-check"></i><b>5.2</b> General functions</a><ul>
<li class="chapter" data-level="5.2.1" data-path="forcats.html"><a href="forcats.html#create"><i class="fa fa-check"></i><b>5.2.1</b> Create</a></li>
<li class="chapter" data-level="5.2.2" data-path="forcats.html"><a href="forcats.html#count-values-per-level"><i class="fa fa-check"></i><b>5.2.2</b> Count values per level</a></li>
<li class="chapter" data-level="5.2.3" data-path="forcats.html"><a href="forcats.html#Inspect-and-set-levels"><i class="fa fa-check"></i><b>5.2.3</b> Inspect and set levels</a></li>
<li class="chapter" data-level="5.2.4" data-path="forcats.html"><a href="forcats.html#inspect-unique-values"><i class="fa fa-check"></i><b>5.2.4</b> Inspect unique values</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="forcats.html"><a href="forcats.html#combine-factors"><i class="fa fa-check"></i><b>5.3</b> Combine factors</a><ul>
<li class="chapter" data-level="5.3.1" data-path="forcats.html"><a href="forcats.html#combine-factors-with-different-levels"><i class="fa fa-check"></i><b>5.3.1</b> Combine factors with different levels</a></li>
<li class="chapter" data-level="5.3.2" data-path="forcats.html"><a href="forcats.html#standardise-levels-of-various-factors"><i class="fa fa-check"></i><b>5.3.2</b> Standardise levels of various factors</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="forcats.html"><a href="forcats.html#order-of-levels"><i class="fa fa-check"></i><b>5.4</b> Order of levels</a><ul>
<li class="chapter" data-level="5.4.1" data-path="forcats.html"><a href="forcats.html#manual-reordering"><i class="fa fa-check"></i><b>5.4.1</b> Manual reordering of levels</a></li>
<li class="chapter" data-level="5.4.2" data-path="forcats.html"><a href="forcats.html#reordering-by-frequency"><i class="fa fa-check"></i><b>5.4.2</b> Reordering by frequency</a></li>
<li class="chapter" data-level="5.4.3" data-path="forcats.html"><a href="forcats.html#reordering-by-appearance"><i class="fa fa-check"></i><b>5.4.3</b> Reordering by appearance</a></li>
<li class="chapter" data-level="5.4.4" data-path="forcats.html"><a href="forcats.html#reverse-level-order"><i class="fa fa-check"></i><b>5.4.4</b> Reverse level order</a></li>
<li class="chapter" data-level="5.4.5" data-path="forcats.html"><a href="forcats.html#shift-levels"><i class="fa fa-check"></i><b>5.4.5</b> Shift levels</a></li>
<li class="chapter" data-level="5.4.6" data-path="forcats.html"><a href="forcats.html#randomly-shuffle-levels"><i class="fa fa-check"></i><b>5.4.6</b> Randomly shuffle levels</a></li>
<li class="chapter" data-level="5.4.7" data-path="forcats.html"><a href="forcats.html#reordering-levels-by-other-variables"><i class="fa fa-check"></i><b>5.4.7</b> Reordering levels by other variables</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="forcats.html"><a href="forcats.html#change-the-value-of-levels"><i class="fa fa-check"></i><b>5.5</b> Change the value of levels</a><ul>
<li class="chapter" data-level="5.5.1" data-path="forcats.html"><a href="forcats.html#renaming-the-levels"><i class="fa fa-check"></i><b>5.5.1</b> Renaming the levels</a></li>
<li class="chapter" data-level="5.5.2" data-path="forcats.html"><a href="forcats.html#anonymize-levels"><i class="fa fa-check"></i><b>5.5.2</b> Anonymize levels</a></li>
<li class="chapter" data-level="5.5.3" data-path="forcats.html"><a href="forcats.html#collapse-multiple-levels-into-one"><i class="fa fa-check"></i><b>5.5.3</b> Collapse multiple levels into one</a></li>
<li class="chapter" data-level="5.5.4" data-path="forcats.html"><a href="forcats.html#aggregate-levels-into-a-lump"><i class="fa fa-check"></i><b>5.5.4</b> Aggregate levels into a lump</a></li>
<li class="chapter" data-level="5.5.5" data-path="forcats.html"><a href="forcats.html#manually-lump-levels"><i class="fa fa-check"></i><b>5.5.5</b> Manually lump levels</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="forcats.html"><a href="forcats.html#add-or-drop-levels"><i class="fa fa-check"></i><b>5.6</b> Add or drop levels</a><ul>
<li class="chapter" data-level="5.6.1" data-path="forcats.html"><a href="forcats.html#add-levels"><i class="fa fa-check"></i><b>5.6.1</b> Add levels</a></li>
<li class="chapter" data-level="5.6.2" data-path="forcats.html"><a href="forcats.html#drop-levels"><i class="fa fa-check"></i><b>5.6.2</b> Drop levels</a></li>
<li class="chapter" data-level="5.6.3" data-path="forcats.html"><a href="forcats.html#assign-a-level-to-nas"><i class="fa fa-check"></i><b>5.6.3</b> Assign a level to <code>NAs</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="stringr.html"><a href="stringr.html"><i class="fa fa-check"></i><b>6</b> Character data: stringr</a><ul>
<li class="chapter" data-level="6.1" data-path="stringr.html"><a href="stringr.html#introduction-1"><i class="fa fa-check"></i><b>6.1</b> Introduction</a><ul>
<li class="chapter" data-level="6.1.1" data-path="stringr.html"><a href="stringr.html#use-of-stringr-in-the-r-environment"><i class="fa fa-check"></i><b>6.1.1</b> Use of stringR in the R environment</a></li>
<li class="chapter" data-level="6.1.2" data-path="stringr.html"><a href="stringr.html#types-of-data-which-could-be-used-with-stringr"><i class="fa fa-check"></i><b>6.1.2</b> Types of data, which could be used with stringR</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="stringr.html"><a href="stringr.html#data-set-for-examples"><i class="fa fa-check"></i><b>6.2</b> Data Set for examples</a></li>
<li class="chapter" data-level="6.3" data-path="stringr.html"><a href="stringr.html#regular-expressions"><i class="fa fa-check"></i><b>6.3</b> Regular Expressions</a></li>
<li class="chapter" data-level="6.4" data-path="stringr.html"><a href="stringr.html#functions-of-stringr-explained"><i class="fa fa-check"></i><b>6.4</b> Functions of stringR explained</a><ul>
<li class="chapter" data-level="6.4.1" data-path="stringr.html"><a href="stringr.html#manage-lengths"><i class="fa fa-check"></i><b>6.4.1</b> Manage lengths</a></li>
<li class="chapter" data-level="6.4.2" data-path="stringr.html"><a href="stringr.html#subset-strings"><i class="fa fa-check"></i><b>6.4.2</b> Subset Strings</a></li>
<li class="chapter" data-level="6.4.3" data-path="stringr.html"><a href="stringr.html#detect-matches"><i class="fa fa-check"></i><b>6.4.3</b> Detect matches</a></li>
<li class="chapter" data-level="6.4.4" data-path="stringr.html"><a href="stringr.html#mutate-strings"><i class="fa fa-check"></i><b>6.4.4</b> Mutate Strings</a></li>
<li class="chapter" data-level="6.4.5" data-path="stringr.html"><a href="stringr.html#join-and-split"><i class="fa fa-check"></i><b>6.4.5</b> Join and Split</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="stringr.html"><a href="stringr.html#literature"><i class="fa fa-check"></i><b>6.5</b> Literature</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="data-table.html"><a href="data-table.html"><i class="fa fa-check"></i><b>7</b> High performance computing: data.table</a><ul>
<li class="chapter" data-level="7.1" data-path="data-table.html"><a href="data-table.html#motivation-1"><i class="fa fa-check"></i><b>7.1</b> Motivation</a></li>
<li class="chapter" data-level="7.2" data-path="data-table.html"><a href="data-table.html#data-exploration"><i class="fa fa-check"></i><b>7.2</b> Data exploration</a><ul>
<li class="chapter" data-level="7.2.1" data-path="data-table.html"><a href="data-table.html#subsetting-rows"><i class="fa fa-check"></i><b>7.2.1</b> Subsetting rows</a></li>
<li class="chapter" data-level="7.2.2" data-path="data-table.html"><a href="data-table.html#selecting-columns"><i class="fa fa-check"></i><b>7.2.2</b> Selecting Columns</a></li>
<li class="chapter" data-level="7.2.3" data-path="data-table.html"><a href="data-table.html#grouping-results"><i class="fa fa-check"></i><b>7.2.3</b> Grouping results</a></li>
<li class="chapter" data-level="7.2.4" data-path="data-table.html"><a href="data-table.html#editing-data"><i class="fa fa-check"></i><b>7.2.4</b> Editing Data</a></li>
<li class="chapter" data-level="7.2.5" data-path="data-table.html"><a href="data-table.html#side-effects"><i class="fa fa-check"></i><b>7.2.5</b> Side effects</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="data-table.html"><a href="data-table.html#runtime-comparision"><i class="fa fa-check"></i><b>7.3</b> Runtime comparision</a></li>
<li class="chapter" data-level="7.4" data-path="data-table.html"><a href="data-table.html#further-resources"><i class="fa fa-check"></i><b>7.4</b> Further resources</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R Data Science Book</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="lubridate" class="section level1">
<h1><span class="header-section-number">4</span> Dates and times: lubridate</h1>
<p>Resources:</p>
<ul>
<li><a href="https://lubridate.tidyverse.org/">Lubridate homepage</a></li>
<li><a href="https://rawgit.com/rstudio/cheatsheets/master/lubridate.pdf">Cheatsheet</a></li>
<li><a href="https://r4ds.had.co.nz/dates-and-times.html">Book Chapter in R4DS</a></li>
<li><a href="https://cran.r-project.org/web/packages/lubridate/vignettes/lubridate.html">Vignette</a></li>
</ul>
<p>Suggested data set: weather-kiel-holtenau</p>
<div id="what-is-lubridate" class="section level2">
<h2><span class="header-section-number">4.1</span> What is Lubridate?</h2>
<p>Lubridate is an R-Package designed to ease working with date/time variables. These can be challenging in baseR and lubridate allows for frictionless working with dates and times, hence the name.</p>
<p>Lubridate ist part of the tidyverse package, but can be installed seperately as well. It probably reveals most of its usefullness in collaboration with other tidyverse packages. A useful extension, depending on your data, might be the time-series package which is not part of tidyverse.</p>
<p>All mentioned packages can be optained with the following commands in the RStudio console.</p>
<p>install.packages(“lubridate”)
install.packages(“tidyverse”)
install.packages(“testit”)</p>
<p>If they have been installed previously in your environment, they might have to be called upon by using library(tidyverse) and so forth - see code chunks below.</p>
</div>
<div id="basics" class="section level2">
<h2><span class="header-section-number">4.2</span> Basics</h2>
<p>Some examples of real world date-time formats found in datasets:</p>
<p>How people talk about dates and times often differs from the notation. Depending on the specific use of the data, the given information might be more or less granular. When people in the USA talk distance between two places, they often give an approximation of how long it will take a person to drive from A to B and round-up or down to the hour.</p>
<p>Flight schedules will most likely be exact to the minute, while some sensordata will probably need to be exact to the second. So there will be differing granularity in date and time data.</p>
<p>Even if this would not be challenging, we still would have to deal with different notations of date and time. People in Germany will write a day-date like: dd.mm.yyyy or short dd.mm.yy, while the anglo-saxon realm will use mm.dd.yyyy frequently and the most chronologically sound way would be to use yyyy.mm.dd, but this doesn’t seem to stick with humans.</p>
<p>On top of these issues there’s the fact that time itself does not make the impression of being the most exact parameter out there. Physical time might appear linear, but the way our planet revolves within our galaxy has made it neccessary to adjust date and times every now and then, so our calendar stays in tune with defined periods and seasons. This creates leap years, skipped seconds, daylight-savings time and last, but not least time-zones, which can mess things up even further. After defining date-time data as distinct “places in time” often the need for calculation with them arises.</p>
</div>
<div id="import-data-clean-date-time" class="section level2">
<h2><span class="header-section-number">4.3</span> Import data, clean date-time</h2>
<p>We will apply the lubridate package to Weather data from on stationary sensor in northern Germany, the weather station in Kiel-Holtenau to be more exact.</p>
<p>Before we introduce the library, the technical prerequisites must be created.</p>
<pre><code>## 
## Attache Paket: &#39;lubridate&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:base&#39;:
## 
##     date</code></pre>
<pre><code>## -- Attaching packages ----- tidyverse 1.2.1 --</code></pre>
<pre><code>## v ggplot2 3.3.0     v purrr   0.3.2
## v tibble  3.0.0     v dplyr   0.8.5
## v tidyr   1.0.0     v stringr 1.4.0
## v ggplot2 3.3.0     v forcats 0.5.0</code></pre>
<pre><code>## Warning: Paket &#39;ggplot2&#39; wurde unter R Version 3.6.3 erstellt</code></pre>
<pre><code>## Warning: Paket &#39;tibble&#39; wurde unter R Version 3.6.3 erstellt</code></pre>
<pre><code>## Warning: Paket &#39;dplyr&#39; wurde unter R Version 3.6.3 erstellt</code></pre>
<pre><code>## Warning: Paket &#39;forcats&#39; wurde unter R Version 3.6.3 erstellt</code></pre>
<pre><code>## -- Conflicts -------- tidyverse_conflicts() --
## x lubridate::as.difftime() masks base::as.difftime()
## x lubridate::date()        masks base::date()
## x dplyr::filter()          masks stats::filter()
## x lubridate::intersect()   masks base::intersect()
## x dplyr::lag()             masks stats::lag()
## x lubridate::setdiff()     masks base::setdiff()
## x lubridate::union()       masks base::union()</code></pre>
<pre><code>## Warning: Paket &#39;testit&#39; wurde unter R Version 3.6.3 erstellt</code></pre>
<p>With the lubridate package activated, we can now call some simple functions to check where we are in time:</p>
<pre><code>## [1] &quot;2020-05-07&quot;</code></pre>
<pre><code>## [1] &quot;2020-05-07 10:32:31 CEST&quot;</code></pre>
<pre><code>## [1] &quot;2020-05-07&quot;</code></pre>
<pre><code>## [1] &quot;2020-05-07 10:32:31 CEST&quot;</code></pre>
<pre><code>## [1] &quot;Europe/Berlin&quot;</code></pre>
<p>The first function delivers a date, while the second delivers a date-time (a date + a time).
The third is a baseR function that produces the date, the operating system sees as current, while the fourth displays the systems full current timestamp. The third and fourth functions are both baseR and therefore case sensitive, while the first and second are lubridate functions which behave just nicer and allow for fluent calculations.</p>
<p>Now let’s have a look at some real world data and the challenges of date-time formatting.</p>
<p>A first step is to import the data, which is given in a csv-format.
We will use the tidyverse version of read_csv to accomplish this step.</p>
<p>The data will be called df (data.frame) in order to make reference in code an writing more efficient further down.</p>
<p>This is the simple approach to read a file with suffix csv.</p>
<pre><code>## Parsed with column specification:
## cols(
##   STATIONS_ID = col_double(),
##   MESS_DATUM = col_double(),
##   TEMPERATUR = col_double(),
##   RELATIVE_FEUCHTE = col_double(),
##   NIEDERSCHLAGSDAUER = col_double(),
##   NIEDERSCHLAGSHOEHE = col_double(),
##   NIEDERSCHLAGSINDIKATOR = col_double()
## )</code></pre>
<pre><code>## # A tibble: 5 x 7
##   STATIONS_ID MESS_DATUM TEMPERATUR RELATIVE_FEUCHTE NIEDERSCHLAGSDA~
##         &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;            &lt;dbl&gt;            &lt;dbl&gt;
## 1        2564    2.02e11        3.6             75.6                0
## 2        2564    2.02e11        3.6             75.6                6
## 3        2564    2.02e11        3.6             76.5                0
## 4        2564    2.02e11        3.5             75.6                0
## 5        2564    2.02e11        3.6             75.3                0
## # ... with 2 more variables: NIEDERSCHLAGSHOEHE &lt;dbl&gt;,
## #   NIEDERSCHLAGSINDIKATOR &lt;dbl&gt;</code></pre>
<p>All columns are recognized as double values.</p>
<p>By looking at the “MESS_DATUM” column it becomes apparent that this represents a timestamp that was created every 10 minutes. The standard column type definition of the import tool has not sufficed to format this appropriately, which is why the column will be defined as a double for now.</p>
<p>Using the code generator of the data import tool it is possible to format the variables in the appropriate classes. The code snippet is automatically generated by the import tool of RStudio. For our concern of the timestamp variable please note the part where the column MESS_DATUM = col_datetime(format = “%Y%m%d%H%M”) which will reach our present goal to format the timestamp and class as a POSIXct.</p>
<pre><code>## # A tibble: 5 x 7
##   STATIONS_ID MESS_DATUM          TEMPERATUR RELATIVE_FEUCHTE NIEDERSCHLAGSDA~
##         &lt;int&gt; &lt;dttm&gt;                   &lt;dbl&gt;            &lt;dbl&gt;            &lt;int&gt;
## 1        2564 2019-04-14 00:00:00        3.6             75.6                0
## 2        2564 2019-04-14 00:10:00        3.6             75.6                6
## 3        2564 2019-04-14 00:20:00        3.6             76.5                0
## 4        2564 2019-04-14 00:30:00        3.5             75.6                0
## 5        2564 2019-04-14 00:40:00        3.6             75.3                0
## # ... with 2 more variables: NIEDERSCHLAGSHOEHE &lt;dbl&gt;,
## #   NIEDERSCHLAGSINDIKATOR &lt;int&gt;</code></pre>
<p>We will examine the data further down below. At this point it should be mentioned again that we generated the code to import the data by using the import readr tool of RStudio. This allows a first look at the raw csv data before import and some tweaking of the variables and their classes. We left the locale portion of the import tool untouched.</p>
<p>The following lines of code import the same data in the MESS_DATUM column as a string of characters again and then call a specific lubridate function (ymd = year-month-day) which basically recognizes the time format in the column given only very little information. In our case we only specify the order in which the date-time information is given, which is Year-Month-Day-Hour-Minute. The ymd_hm function delivers the desired result however, only if it is applied to a character string, which is why we chose to overwrite the dataset df with a new import procedure that makes sure that the column MESS_DATUM is given as a character after import in order to be then transformed to a date-time.</p>
<pre><code>## # A tibble: 5 x 7
##   STATIONS_ID MESS_DATUM          TEMPERATUR RELATIVE_FEUCHTE NIEDERSCHLAGSDA~
##         &lt;int&gt; &lt;dttm&gt;                   &lt;dbl&gt;            &lt;dbl&gt;            &lt;dbl&gt;
## 1        2564 2019-04-14 00:00:00        3.6             75.6                0
## 2        2564 2019-04-14 00:10:00        3.6             75.6                6
## 3        2564 2019-04-14 00:20:00        3.6             76.5                0
## 4        2564 2019-04-14 00:30:00        3.5             75.6                0
## 5        2564 2019-04-14 00:40:00        3.6             75.3                0
## # ... with 2 more variables: NIEDERSCHLAGSHOEHE &lt;dbl&gt;,
## #   NIEDERSCHLAGSINDIKATOR &lt;int&gt;</code></pre>
<p>As can be seen above, the MESS_DATUM is now in a POSIXct format again, which is what will be needed for further calculations and analysis of the data set.</p>
<p>Alternatively you could use the following parsing function to achieve the same result. Note that the parse_date_time function of lubridate also needs the timestamp to be in character format in order to work.</p>
<pre><code>## # A tibble: 5 x 7
##   STATIONS_ID MESS_DATUM          TEMPERATUR RELATIVE_FEUCHTE NIEDERSCHLAGSDA~
##         &lt;dbl&gt; &lt;dttm&gt;                   &lt;dbl&gt;            &lt;dbl&gt;            &lt;dbl&gt;
## 1        2564 2019-04-14 00:00:00        3.6             75.6                0
## 2        2564 2019-04-14 00:10:00        3.6             75.6                6
## 3        2564 2019-04-14 00:20:00        3.6             76.5                0
## 4        2564 2019-04-14 00:30:00        3.5             75.6                0
## 5        2564 2019-04-14 00:40:00        3.6             75.3                0
## # ... with 2 more variables: NIEDERSCHLAGSHOEHE &lt;dbl&gt;,
## #   NIEDERSCHLAGSINDIKATOR &lt;dbl&gt;</code></pre>
<p>OK, we have successfully formated the time-stamp data into a productive date-time (dttm) format using three different aproaches.</p>
</div>
<div id="check-and-modify-data" class="section level2">
<h2><span class="header-section-number">4.4</span> Check and modify data</h2>
<p>The next steps are a check and elimination procedure to eliminate missing values (NAs) from the dataset,
if some observations might have failed to generate a timestamp.</p>
<pre><code>## # A tibble: 0 x 7
## # ... with 7 variables: STATIONS_ID &lt;int&gt;, MESS_DATUM &lt;dttm&gt;, TEMPERATUR &lt;dbl&gt;,
## #   RELATIVE_FEUCHTE &lt;dbl&gt;, NIEDERSCHLAGSDAUER &lt;int&gt;, NIEDERSCHLAGSHOEHE &lt;dbl&gt;,
## #   NIEDERSCHLAGSINDIKATOR &lt;int&gt;</code></pre>
<p>We don’t encounter any NAs in the MESS_DATUM column. Eliminating NAs from the MESS_DATUM Column including the other variables of that specific observations from the data frame would have been possible with:</p>
<p>Now it is time to have a first explorative look at the data set.</p>
<pre><code>## [1] &quot;2020-04-13 23:50:00 UTC&quot;</code></pre>
<pre><code>## [1] &quot;2019-04-14 UTC&quot;</code></pre>
<pre><code>## [1] &quot;2019-04-14 00:00:00 UTC&quot; &quot;2020-04-13 23:50:00 UTC&quot;</code></pre>
<p>We are dealing with data over the course of one year starting on midnight 14th April 2019 until 10 minutes to midnight on 13th April 2020.</p>
<p>To gather some information on the other variables we can use the range function again.</p>
<pre><code>## [1] 2564 2564</code></pre>
<pre><code>## [1] -2.5 32.1</code></pre>
<pre><code>## [1] -999  100</code></pre>
<pre><code>## [1] -999   10</code></pre>
<pre><code>## [1] -999.00    7.85</code></pre>
<pre><code>## [1] -999    1</code></pre>
<p>Here we find observations in a number of variables that would need to be deleted from the table to get operable data.
Theoretically, the following columns are only relevant if the NIEDERSCHLAGSINDIKATOR is set to 1 = rainfall. This column can be considered like a switch for the other two rain-connected columns:
- NIEDERSCHLAGSDAUER
- NIEDERSCHLAGSHOEHE</p>
<p>Getting an idea about the extent of weird/failed observations can be accomplished with the following code snippet:</p>
<pre><code>## # A tibble: 3 x 2
##   NIEDERSCHLAGSINDIKATOR     n
##                    &lt;int&gt; &lt;int&gt;
## 1                   -999   127
## 2                      0 43290
## 3                      1  9287</code></pre>
<p>So 127 observations of rainfall are faulty. To modify the NIEDERSCHLAGSINDIKATOR for upcoming analysis we do the following in order to set the -999 Values to a more neutral Zero:</p>
<pre><code>## # A tibble: 2 x 2
##   NIEDERSCHLAGSINDIKATOR     n
##                    &lt;dbl&gt; &lt;int&gt;
## 1                      0 43417
## 2                      1  9287</code></pre>
<p>We now have a binary indicator of rainfall. Over the course of the observed year it rained 9287/43417*100 = 21.4% of the time frames observed.</p>
<p>The column RELATIVE_FEUCHTE must also be adjusted in the same way.</p>
<pre><code>## # A tibble: 1 x 2
##   RELATIVE_FEUCHTE     n
##              &lt;dbl&gt; &lt;int&gt;
## 1             -999   128</code></pre>
<p>The negative values are set to 0 again.</p>
<pre><code>## # A tibble: 6 x 2
##   RELATIVE_FEUCHTE     n
##              &lt;dbl&gt; &lt;int&gt;
## 1              0     128
## 2             25       1
## 3             25.4     1
## 4             25.5     1
## 5             25.8     1
## 6             26.3     1</code></pre>
<p>The column NIEDERSCHLAGSHOEHE can also be tested and adjusted in the same way.
This is not strictly necessary since the negative values could be hidden from further analysis using the NIEDERSCHLAGSINDIKATOR = 1.</p>
<pre><code>## # A tibble: 1 x 2
##   NIEDERSCHLAGSHOEHE     n
##                &lt;dbl&gt; &lt;int&gt;
## 1               -999   129</code></pre>
<p>The negative values are set to 0 again.</p>
<pre><code>## # A tibble: 6 x 2
##   NIEDERSCHLAGSHOEHE     n
##                &lt;dbl&gt; &lt;int&gt;
## 1               0    47753
## 2               0.01   712
## 3               0.02   343
## 4               0.03   377
## 5               0.04   397
## 6               0.05   234</code></pre>
<p>We have set Variable NIEDERSCHLAGSHOEHE to 0 in these 129 oberservations. In a total of 47,753 observations with 0 as a value the distortion this might cause can be called negligible.</p>
</div>
<div id="before-exploration" class="section level2">
<h2><span class="header-section-number">4.5</span> Before exploration</h2>
<p>We now have clean and tidy data and can begin with general exploration, analysis and interpretation.</p>
<p>The “TEMPERATUR” is given in degrees Celsius, the “RELATIVE-FEUCHTE” is a percentage Value for humidity which refers to the degree of water saturation that is prevalent in the air at a given temperature. As temperature increases, the air can absorb larger amounts of water, hence the relativity of this variable.</p>
<p>The next variable is “NIEDERSCHLAGSDAUER” which is given as an integer smaller or equal to 10. Therefore it gives the time it has rained during the timestamp interval of 10 Minutes.</p>
<p>The variable “NIEDERSCHLAGSHOEHE” is a measure of rainfall intensity. Its maximum value can also be checked by the following command:</p>
<pre><code>## [1] 7.85</code></pre>
<p>We can assume that this number gives us the amount of rainfall in milimeters, which is a common definiton and is equivalent as liters of rainfall per squaremeter in a given time interval. A strong rainfall in central Europe can be expected to generate around 30mm/h of rainfall, i.e. 30 liters per squaremeter per hour. The maximum value is therefore an indicator of a very heavy downpour as a continuation for a whole hour would have yielded 6 x 7.85 = 47.1 litres per hour.</p>
<p>The next variable is simply a binary expression of rainfall (1) or no rainfall (0) in the given interval. This is relevant to measure as some types of rainfall seem to not generate enough water to messure an actual amount of water. The dreaded Northgerman “drizzle” comes to mind.</p>
<p>Again: Since the sensor has taken a snapshot every 10 minutes, we have six observations per hour.</p>
<div id="intervals" class="section level3">
<h3><span class="header-section-number">4.5.1</span> Intervals</h3>
<p>Lubridate allows for the definition of an interval object with the “interval” class. The interval is simply defined as the time elapsed between two points on the date-time line.</p>
<p>e.g. The interval of a single day - from the first of March to the second of March can be defined as follows:</p>
<pre><code>## [1] &quot;Interval&quot;
## attr(,&quot;package&quot;)
## [1] &quot;lubridate&quot;</code></pre>
<pre><code>## [1] &quot;2020-03-01 UTC&quot; &quot;2020-03-02 UTC&quot;</code></pre>
<p>This small interval of one day turned out to be good for further analysis.
This makes it easier to check results at a glance without having to query the whole dataset.</p>
<p>When the desired results can be achieved for a small interval we could consider the next largest period, e.g. Week, month, quarter and year.</p>
<div id="durations-and-periods" class="section level4">
<h4><span class="header-section-number">4.5.1.1</span> Durations and periods</h4>
<p>For any weather data, an analysis of seasonal differences is a natural (excuse the pun) objective.
The beginning of each years seasons align with the solar incidences, i.e. the spring and autumnal equinoxes and the days of most and least sunlight hours in summer and winter, respectively.</p>
<p>The following code snippets define the starting points of the different seasons as points on the POSIXct timeline and use these points to calculate new points by later adding durations and periods to them.</p>
<p>For a seasons view, we create the appropriate points in time, where each season begins.</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb92-1" title="1">season_<span class="dv">19</span>_spring &lt;-<span class="st"> </span><span class="kw">ymd_hm</span>(<span class="st">&quot;2019-03-20 22:58&quot;</span>, <span class="dt">tz=</span><span class="st">&quot;CET&quot;</span>)</a>
<a class="sourceLine" id="cb92-2" title="2">season_<span class="dv">19</span>_summer &lt;-<span class="st"> </span><span class="kw">ymd_hm</span>(<span class="st">&quot;2019-06-21 17:54&quot;</span>, <span class="dt">tz=</span><span class="st">&quot;CET&quot;</span>)</a>
<a class="sourceLine" id="cb92-3" title="3">season_<span class="dv">19</span>_autumn &lt;-<span class="st"> </span><span class="kw">ymd_hm</span>(<span class="st">&quot;2019-09-23 09:50&quot;</span>, <span class="dt">tz=</span><span class="st">&quot;CET&quot;</span>)</a>
<a class="sourceLine" id="cb92-4" title="4">season_<span class="dv">19</span>_winter &lt;-<span class="st"> </span><span class="kw">ymd_hm</span>(<span class="st">&quot;2019-12-22 05:19&quot;</span>, <span class="dt">tz=</span><span class="st">&quot;CET&quot;</span>)</a>
<a class="sourceLine" id="cb92-5" title="5">season_<span class="dv">20</span>_spring &lt;-<span class="st"> </span><span class="kw">ymd_hm</span>(<span class="st">&quot;2020-03-20 04:49&quot;</span>, <span class="dt">tz=</span><span class="st">&quot;CET&quot;</span>)</a>
<a class="sourceLine" id="cb92-6" title="6">season_<span class="dv">20</span>_summer &lt;-<span class="st"> </span><span class="kw">ymd_hm</span>(<span class="st">&quot;2020-06-20 23:43&quot;</span>, <span class="dt">tz=</span><span class="st">&quot;CET&quot;</span>)</a></code></pre></div>
<p>Source re: starts of seasons <a href="https://www.timeanddate.de/astronomie/jahreszeiten" title="timeanddate.de">from</a></p>
<p>Our goal shall be to create an interval for the spring season.
The following information is available to determine the end point of spring:
<strong>Frühling</strong> 2020
Beginn (Tag-und-Nachtgleiche März)
20. März 04:49
Dauer 92 Tage, 17 Std, 54 Min
<strong>Sommer</strong> 2020
Beginn (Sonnenwende Juni)
20. Juni 23:43
Dauer 93 Tage, 15 Std, 46 Min</p>
<div id="durations" class="section level5">
<h5><span class="header-section-number">4.5.1.1.1</span> Durations</h5>
<p>First approach is with the object DURATIONS of lubridate:</p>
<pre><code>## [1] &quot;spring 2020 - start:  2020-03-20 04:49:00&quot;</code></pre>
<pre><code>## [1] &quot;7948800s (~13.14 weeks)&quot;</code></pre>
<pre><code>## [1] &quot;Duration&quot;
## attr(,&quot;package&quot;)
## [1] &quot;lubridate&quot;</code></pre>
<pre><code>## [1] &quot;double&quot;</code></pre>
<pre><code>## [1] &quot;2020-06-20 23:43:00 CEST&quot;</code></pre>
<pre><code>## [1] &quot;POSIXct&quot; &quot;POSIXt&quot;</code></pre>
<pre><code>## [1] &quot;double&quot;</code></pre>
<pre><code>## [1] &quot;spring 2020-end of DURATIONS: 2020-06-20 23:43:00 expected: 2020-06-20 23:43:00 is failure: FALSE&quot;</code></pre>
</div>
<div id="periods" class="section level5">
<h5><span class="header-section-number">4.5.1.1.2</span> Periods</h5>
<p>Second approach is with the object PERIODS of lubridate:</p>
<pre><code>## [1] &quot;92d 0H 0M 0S&quot;</code></pre>
<pre><code>## [1] &quot;Period&quot;
## attr(,&quot;package&quot;)
## [1] &quot;lubridate&quot;</code></pre>
<pre><code>## [1] &quot;double&quot;</code></pre>
<pre><code>## [1] &quot;2020-06-20 22:43:00 CEST&quot;</code></pre>
<pre><code>## [1] &quot;POSIXct&quot; &quot;POSIXt&quot;</code></pre>
<pre><code>## [1] &quot;double&quot;</code></pre>
<pre><code>## [1] &quot;spring 2020-end of PERIODS: 2020-06-20 22:43:00 expected: 2020-06-20 23:43:00 is failure: TRUE&quot;</code></pre>
<p>This example shows that the use of PERIODS or DURATIONS must be weighed up and balanced depending on what are you looking for.
The periods-example has a difference of one hour to the durations-example, because its clock-time takes daylight savings time shift.</p>
</div>
</div>
<div id="math-with-periods" class="section level4">
<h4><span class="header-section-number">4.5.1.2</span> Math with periods</h4>
<p>Using starting points of seasons summer, autumn and winter to create intervals for our data frame.</p>
</div>
</div>
<div id="groupings" class="section level3">
<h3><span class="header-section-number">4.5.2</span> Groupings</h3>
<p>What follows is preliminary step working with group_bys and renames in order to then apply the findings to seasons again.</p>
<p>The following GROUP_BY command creates a unique grouping per hour and then calculates the average temperature for every hour, then pastes this value into each observation per hour.</p>
<pre><code>## # A tibble: 10 x 9
## # Groups:   STATIONS_ID, hour(MESS_DATUM), day(MESS_DATUM) [2]
##    STATIONS_ID MESS_DATUM          TEMPERATUR RELATIVE_FEUCHTE NIEDERSCHLAGSDA~
##          &lt;int&gt; &lt;dttm&gt;                   &lt;dbl&gt;            &lt;dbl&gt;            &lt;int&gt;
##  1        2564 2020-03-01 00:00:00        5.2             71.1                0
##  2        2564 2020-03-01 00:10:00        5.4             69.5                0
##  3        2564 2020-03-01 00:20:00        5.5             68.2                0
##  4        2564 2020-03-01 00:30:00        5.6             68.3                0
##  5        2564 2020-03-01 00:40:00        5.5             69                  0
##  6        2564 2020-03-01 00:50:00        5.5             69.1                0
##  7        2564 2020-03-01 01:00:00        5.4             69.7                0
##  8        2564 2020-03-01 01:10:00        5.3             70                  0
##  9        2564 2020-03-01 01:20:00        5.3             69.9                0
## 10        2564 2020-03-01 01:30:00        5.2             71                  0
## # ... with 4 more variables: NIEDERSCHLAGSHOEHE &lt;dbl&gt;,
## #   NIEDERSCHLAGSINDIKATOR &lt;dbl&gt;, `hour(MESS_DATUM)` &lt;int&gt;,
## #   `day(MESS_DATUM)` &lt;int&gt;</code></pre>
<p>For better readability, the columns can be renamed after a Group-By with rename function.</p>
<pre><code>## # A tibble: 10 x 9
## # Groups:   STATIONS_ID, STUNDE, TAG [2]
##    STATIONS_ID MESS_DATUM          TEMPERATUR RELATIVE_FEUCHTE NIEDERSCHLAGSDA~
##          &lt;int&gt; &lt;dttm&gt;                   &lt;dbl&gt;            &lt;dbl&gt;            &lt;int&gt;
##  1        2564 2020-03-01 00:00:00        5.2             71.1                0
##  2        2564 2020-03-01 00:10:00        5.4             69.5                0
##  3        2564 2020-03-01 00:20:00        5.5             68.2                0
##  4        2564 2020-03-01 00:30:00        5.6             68.3                0
##  5        2564 2020-03-01 00:40:00        5.5             69                  0
##  6        2564 2020-03-01 00:50:00        5.5             69.1                0
##  7        2564 2020-03-01 01:00:00        5.4             69.7                0
##  8        2564 2020-03-01 01:10:00        5.3             70                  0
##  9        2564 2020-03-01 01:20:00        5.3             69.9                0
## 10        2564 2020-03-01 01:30:00        5.2             71                  0
## # ... with 4 more variables: NIEDERSCHLAGSHOEHE &lt;dbl&gt;,
## #   NIEDERSCHLAGSINDIKATOR &lt;dbl&gt;, STUNDE &lt;int&gt;, TAG &lt;int&gt;</code></pre>
<p>Or the columns can be named directly in the Group-By command:</p>
<pre><code>## # A tibble: 5 x 9
## # Groups:   STATIONS_ID, STUNDE, TAG [1]
##   STATIONS_ID MESS_DATUM          TEMPERATUR RELATIVE_FEUCHTE NIEDERSCHLAGSDA~
##         &lt;int&gt; &lt;dttm&gt;                   &lt;dbl&gt;            &lt;dbl&gt;            &lt;int&gt;
## 1        2564 2020-03-01 00:00:00        5.2             71.1                0
## 2        2564 2020-03-01 00:10:00        5.4             69.5                0
## 3        2564 2020-03-01 00:20:00        5.5             68.2                0
## 4        2564 2020-03-01 00:30:00        5.6             68.3                0
## 5        2564 2020-03-01 00:40:00        5.5             69                  0
## # ... with 4 more variables: NIEDERSCHLAGSHOEHE &lt;dbl&gt;,
## #   NIEDERSCHLAGSINDIKATOR &lt;dbl&gt;, STUNDE &lt;int&gt;, TAG &lt;int&gt;</code></pre>
<p>Now we can filter the data by year, month, week, day and hour of the day. This should give us possibilities to aggregate freely over any time specifications.</p>
<div id="seasons" class="section level4">
<h4><span class="header-section-number">4.5.2.1</span> Seasons</h4>
<p>Now we create data frames for analysing seasons.</p>
<div id="spring" class="section level5">
<h5><span class="header-section-number">4.5.2.1.1</span> Spring</h5>
<p>We do not consider spring as our data frame is not complete for this period.</p>
</div>
<div id="summer" class="section level5">
<h5><span class="header-section-number">4.5.2.1.2</span> Summer</h5>
<p>The challenge when selecting summer dates is the time zone.</p>
<pre><code>## [1] &quot;2019-06-21 16:00:00 UTC&quot; &quot;2019-09-23 07:40:00 UTC&quot;</code></pre>
<p>If the expected number of data records does not match the currently determined number, the further analysis should not be continued or repeated.
With the help of assurances(assert) logical errors in programs or analysis can be identified and ended in a controlled manner, if necessary.</p>
<pre><code>## [1] &quot;summer min and max 2019-06-21 16:00:00 2019-09-23 07:40:00&quot;</code></pre>
<p>Our first approach gets the correct number of records, but not the expected record with the first interval value ‘2019-06-21 18:00’.</p>
<p>To find For the analysis of start and end time points we use the stamp function of lubridate.</p>
<pre><code>## Multiple formats matched: &quot;set to %d %Om %Y %H:%M&quot;(1), &quot;set to %d %b %Y %H:%M&quot;(1)</code></pre>
<pre><code>## Using: &quot;set to %d %b %Y %H:%M&quot;</code></pre>
<pre><code>## [1] &quot;set to 21 Jun 2019 17:54&quot;</code></pre>
<pre><code>## [1] &quot;set to 23 Sep 2019 09:49&quot;</code></pre>
<pre><code>## Multiple formats matched: &quot;set to Monday, %d.%Om.%Y %H:%M&quot;(1), &quot;set to Monday, %d.%m.%Y %H:%M&quot;(1)</code></pre>
<pre><code>## Using: &quot;set to Monday, %d.%Om.%Y %H:%M&quot;</code></pre>
<pre><code>## [1] &quot;set to Monday, 21.06.2019 17:54&quot;</code></pre>
<pre><code>## [1] &quot;set to Monday, 23.09.2019 09:49&quot;</code></pre>
<pre><code>## Multiple formats matched: &quot;Created Sunday, %Om %d, %Y %H:%M&quot;(1), &quot;Created Sunday, %b %d, %Y %H:%M&quot;(1)</code></pre>
<pre><code>## Using: &quot;Created Sunday, %b %d, %Y %H:%M&quot;</code></pre>
<pre><code>## [1] &quot;Created Sunday, Apr 05, 2010 00:00&quot;</code></pre>
<pre><code>## [1] &quot;Created Sunday, Jun 21, 2019 17:54&quot;</code></pre>
<pre><code>## [1] &quot;Created Sunday, Sep 23, 2019 09:49&quot;</code></pre>
<pre><code>## Multiple formats matched: &quot;Created %Om.%d.%Y %H:%M&quot;(1), &quot;Created %d.%Om.%Y %H:%M&quot;(1), &quot;Created %m.%d.%Y %H:%M&quot;(1), &quot;Created %d.%m.%Y %H:%M&quot;(1)</code></pre>
<pre><code>## Using: &quot;Created %Om.%d.%Y %H:%M&quot;</code></pre>
<pre><code>## [1] &quot;Created 04.05.2010 00:00&quot;</code></pre>
<pre><code>## [1] &quot;Created 06.21.2019 17:54&quot;</code></pre>
<pre><code>## [1] &quot;Created 09.23.2019 09:49&quot;</code></pre>
<p>The function stamp could be a useful function of lubridate, in our opinion a little bit hard to configure.</p>
<pre><code>## [1] &quot;21.06.2019-17:54&quot;</code></pre>
<pre><code>## [1] &quot;23.09.2019-09:49&quot;</code></pre>
<pre><code>## [1] &quot;Summer start/End format 21.06.2019-17:54 23.09.2019-09:49&quot;</code></pre>
<pre><code>## [1] &quot;Summer start/End 2019-06-21 17:54:00 2019-09-23 09:49:00&quot;</code></pre>
<p>If we do not set the time zone correctly, we get the expected number of data records with our current data frame, but with a time delay.
Select data with timezone format of the data frames first row.</p>
<pre><code>## [1] &quot;2019-04-14 00:00:00 UTC&quot; &quot;2020-04-13 23:50:00 UTC&quot;</code></pre>
<pre><code>## [1] &quot;2019-06-21 16:00:00 UTC&quot; &quot;2019-09-23 07:40:00 UTC&quot;</code></pre>
<pre><code>## [1] &quot;2019-06-21 16:00:00 UTC&quot; &quot;2019-09-23 07:40:00 UTC&quot;</code></pre>
<pre><code>## [1] &quot;with TZ start/end 2019-06-21 15:54:00 / 2019-09-23 07:49:00&quot;</code></pre>
<pre><code>## [1] &quot;Force TZ start/end 2019-06-21 17:54:00 / 2019-09-23 09:49:00&quot;</code></pre>
<pre><code>## [1] &quot;2019-06-21 18:00:00 UTC&quot; &quot;2019-09-23 09:40:00 UTC&quot;</code></pre>
<p>We check our data frame again.</p>
<pre><code>## [1] &quot;summer min and max 2019-06-21 18:00:00 2019-09-23 09:40:00&quot;</code></pre>
</div>
<div id="autumn" class="section level5">
<h5><span class="header-section-number">4.5.2.1.3</span> Autumn</h5>
<p>New attempt to set the start and end points of an interval with the lubridate functions floor_date() and round_date().</p>
<pre><code>## [1] &quot;Autmn start/end 2019-09-23 09:50:00 / 2019-12-22 05:19:00&quot;</code></pre>
<pre><code>## [1] &quot;Round hour 2019-09-23 10:00:00&quot;</code></pre>
<pre><code>## [1] &quot;Round minute 2019-12-22 05:00:00&quot;</code></pre>
<pre><code>## [1] &quot;Autmn start/end 2019-09-23 10:00:00 / 2019-12-22 05:00:00&quot;</code></pre>
<p>These results are not completly satisfying.
So we use our aproach from summer selection of data.</p>
<pre><code>## [1] &quot;Force TZ start/end 2019-09-23 09:50:00 / 2019-12-22 05:18:00&quot;</code></pre>
<pre><code>## # A tibble: 1 x 1
##       n
##   &lt;int&gt;
## 1 12933</code></pre>
<pre><code>## # A tibble: 10 x 8
## # Groups:   STATIONS_ID, TAG [1]
##    STATIONS_ID MESS_DATUM          TEMPERATUR RELATIVE_FEUCHTE NIEDERSCHLAGSDA~
##          &lt;int&gt; &lt;dttm&gt;                   &lt;dbl&gt;            &lt;dbl&gt;            &lt;int&gt;
##  1        2564 2019-09-23 09:50:00       18.8             66.7                0
##  2        2564 2019-09-23 10:00:00       18.9             64.5                0
##  3        2564 2019-09-23 10:10:00       19.5             61.3                0
##  4        2564 2019-09-23 10:20:00       18.9             59.7                0
##  5        2564 2019-09-23 10:30:00       19.4             58.2                0
##  6        2564 2019-09-23 10:40:00       19.6             55.9                0
##  7        2564 2019-09-23 10:50:00       19.8             55.8                0
##  8        2564 2019-09-23 11:00:00       20.2             56.1                0
##  9        2564 2019-09-23 11:10:00       20               57                  0
## 10        2564 2019-09-23 11:20:00       19.3             68.9                0
## # ... with 3 more variables: NIEDERSCHLAGSHOEHE &lt;dbl&gt;,
## #   NIEDERSCHLAGSINDIKATOR &lt;dbl&gt;, TAG &lt;int&gt;</code></pre>
<pre><code>## [1] &quot;2019-09-23 09:50:00 UTC&quot; &quot;2019-12-22 05:10:00 UTC&quot;</code></pre>
</div>
<div id="winter" class="section level5">
<h5><span class="header-section-number">4.5.2.1.4</span> Winter</h5>
<pre><code>## [1] &quot;Force TZ start/end 2019-12-22 05:19:00 / 2020-03-20 04:48:00&quot;</code></pre>
<pre><code>## [1] &quot;2019-12-22 05:20:00 UTC&quot; &quot;2020-03-20 04:40:00 UTC&quot;</code></pre>
</div>
</div>
</div>
</div>
<div id="exploration---analysis" class="section level2">
<h2><span class="header-section-number">4.6</span> Exploration - Analysis</h2>
<p>First we are going to calculate average temperatures for different standard intervalls like hours, days, weeks, months. We will visualise some data and eventually calculate new variables or aggregates for humdity, rainfall etc. as well, plus more insights, that might not be apparent at this stage.</p>
<div id="temperatur" class="section level3">
<h3><span class="header-section-number">4.6.1</span> Temperatur</h3>
<p>The first variable of interest should be “TEMPERATUR”. A quick visualisation delivers this picture:
<img src="lubridate_files/figure-html/ggplot%20MESS_DATUM%20TEMPERATUR%20for%20JAHR-1.png" width="672" />
This is a representation of all 52,704 observations of temperature and naturally appears quite crowded.
However, a typical course of the seasons during a year can already be interpreted from this plot.
Please note that the chart starts at the start of the observations (April 2019) and stretches over a year from there.</p>
<p>Let’S try to get a clearer picture of the temperature variable during the course of the observed year.
We need to form averages and aggregates to make visualisation more to the point and get less crowded pictures.</p>
<p>New variables should represent other dimensions of date-time data. We can use lubridate functions to produce variables for hours, 24hdays, weeks, months and even possibly seasons.</p>
<p>Assigning a year to every observation by creating a new column with lubridate function “year”:</p>
<p>Assigning the specific month (number) to every observation by creating a new column with lubridate function “month”</p>
<p>Assigning an Epiweeknr (EKW = Epi Kalender Woche) to every observation through a column with the function “epiweek”:</p>
<p>Assigning a daynumber to every observation by creating a new column “JTAG” (Year day):</p>
<p>Assigning an hour to every observation by creating a new column “STUNDE”:</p>
<p>Our data frame (df) has 12 variables now and thus we can filter the data by year, month, week, day and hour of the day. This gives us new possibilities to aggregate.</p>
<p>The following GROUP_BY command creates a unique grouping per hour and then calculates the average temperature for every hour, then pastes this value into each observation per hour.</p>
<p>This newly created table has reduced the number of observations by the factor 6 to 8,784 and reveals the average temperature per hour.</p>
<p>Let’s plot the data again as hourly temperature averages per day:
<img src="lubridate_files/figure-html/ggplot%20avg%20TEMPERATUR%20STUNDE-1.png" width="672" />
We can see that the data has become aggregated and that the temperature picture becomes somewhat more clear.
Also the visualisation now stretches over the course of a whole calendar year from left to right.
Let’s go one step further and shorten the data down to daily averages by:</p>
<pre><code>## # A tibble: 10 x 6
## # Groups:   STATIONS_ID, JAHR, MONAT, EKW [2]
##    STATIONS_ID  JAHR MONAT   EKW  JTAG AVGTEMPD
##          &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
##  1        2564  2019     4    16   104     4.96
##  2        2564  2019     4    16   105     5.58
##  3        2564  2019     4    16   106     6.43
##  4        2564  2019     4    16   107     8.17
##  5        2564  2019     4    16   108     9.25
##  6        2564  2019     4    16   109     9.63
##  7        2564  2019     4    16   110     8.91
##  8        2564  2019     4    17   111    11.4 
##  9        2564  2019     4    17   112    12.2 
## 10        2564  2019     4    17   113    12.6</code></pre>
<p>This newly created table has reduced the number of observations by the factor 24 to 366 (the number of days in a leap year) and reveals the average temperature per day.
Let’s plot the data again as dayly temperature averages over the whole period as a line:
<img src="lubridate_files/figure-html/ggplot%20avg%20TEMPERATUR%20JTAG-1.png" width="672" />
The data starts to make even more visual sense. The key take-aways from this plot, next to the rather trivial finding of higher summer temperatures, is the rather high volatility that appears to be attached to daily average temperature throughout the year. This could be interpreted as the changes between high and low pressure weather systems that cross northern Germany.</p>
<p>Let’s boil the data down to weekly temperature averages:</p>
<pre><code>## # A tibble: 10 x 5
## # Groups:   STATIONS_ID, JAHR, MONAT [3]
##    STATIONS_ID  JAHR MONAT   EKW AVGTEMPW
##          &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
##  1        2564  2019     4    16     7.56
##  2        2564  2019     4    17    13.2 
##  3        2564  2019     4    18    10.4 
##  4        2564  2019     5    18     6.66
##  5        2564  2019     5    19     8.43
##  6        2564  2019     5    20    10.2 
##  7        2564  2019     5    21    13.4 
##  8        2564  2019     5    22    12.9 
##  9        2564  2019     6    22    16.3 
## 10        2564  2019     6    23    17.7</code></pre>
<p>and plot again:
<img src="lubridate_files/figure-html/ggplot%20avg%20TEMPERATUR%20WOCHE-1.png" width="672" />
Even in weekyl aggregates of temperature averages the resulting visualisation still tells a story of volatility.
Let’s look at monthly averages:</p>
<pre><code>## # A tibble: 12 x 4
## # Groups:   STATIONS_ID, JAHR [2]
##    STATIONS_ID  JAHR MONAT AVGTEMPM
##          &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
##  1        2564  2019     4    10.4 
##  2        2564  2019     5    10.6 
##  3        2564  2019     6    17.9 
##  4        2564  2019     7    17.3 
##  5        2564  2019     8    18.4 
##  6        2564  2019     9    14.0 
##  7        2564  2019    10    10.8 
##  8        2564  2019    11     6.16
##  9        2564  2019    12     5.20
## 10        2564  2020     1     5.74
## 11        2564  2020     2     5.74
## 12        2564  2020     3     5.58</code></pre>
<p>and plot again:
<img src="lubridate_files/figure-html/ggplot%20avg%20TEMPERATUR%20MONAT-1.png" width="672" />
Which is the kind of temperature curve we would expect to see in a north German location like Kiel with a clear pattern of 3 months of summer with higher average temperatures just below 20 degrees.</p>
<p>It is interesting to note that (at least the first half of April 2020 is apparently much warmer on average than the second half of April in 2019. The dimension indicates a difference of about 2 degrees celsius, a significant difference.</p>
<div id="average-temperature-for-a-day" class="section level4">
<h4><span class="header-section-number">4.6.1.1</span> Average temperature for a day</h4>
<p>Generally, no separate variables would have to be created to determine the average temperatures. The values can be gleaned differently from the data frame.</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb155-1" title="1">df_avg1 &lt;-<span class="st"> </span>df_group <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb155-2" title="2"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avg =</span> <span class="kw">mean</span>(TEMPERATUR)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb155-3" title="3"><span class="st">  </span><span class="kw">arrange</span>( STATIONS_ID , TAG , STUNDE) </a>
<a class="sourceLine" id="cb155-4" title="4"><span class="kw">head</span>(df_avg1, <span class="dv">10</span>) </a></code></pre></div>
<pre><code>## # A tibble: 10 x 4
## # Groups:   STATIONS_ID, STUNDE [10]
##    STATIONS_ID STUNDE   TAG   avg
##          &lt;int&gt;  &lt;int&gt; &lt;int&gt; &lt;dbl&gt;
##  1        2564      0     1  5.45
##  2        2564      1     1  5.32
##  3        2564      2     1  5.22
##  4        2564      3     1  5.3 
##  5        2564      4     1  5.53
##  6        2564      5     1  5.58
##  7        2564      6     1  5.35
##  8        2564      7     1  5.9 
##  9        2564      8     1  6.18
## 10        2564      9     1  6.5</code></pre>
</div>
</div>
<div id="rainfall" class="section level3">
<h3><span class="header-section-number">4.6.2</span> Rainfall</h3>
<div id="sum-with-condition" class="section level4">
<h4><span class="header-section-number">4.6.2.1</span> Sum with condition</h4>
<p>The question here is, how long has ist rained during an hour/day?
There are two different possible aproaches. One is without the binary indicator and the other uses it as a switch.</p>
<p>Without indicator</p>
<pre><code>## # A tibble: 24 x 4
## # Groups:   STATIONS_ID, STUNDE [24]
##    STATIONS_ID STUNDE   TAG `sum(NIEDERSCHLAGSDAUER)`
##          &lt;int&gt;  &lt;int&gt; &lt;int&gt;                     &lt;int&gt;
##  1        2564      0     1                         0
##  2        2564      1     1                         0
##  3        2564      2     1                         0
##  4        2564      3     1                         0
##  5        2564      4     1                         0
##  6        2564      5     1                         0
##  7        2564      6     1                         0
##  8        2564      7     1                         0
##  9        2564      8     1                         0
## 10        2564      9     1                         0
## # ... with 14 more rows</code></pre>
<p>With indicator and renamed column</p>
<pre><code>## # A tibble: 24 x 4
## # Groups:   STATIONS_ID, STUNDE [24]
##    STATIONS_ID STUNDE   TAG MENGE
##          &lt;int&gt;  &lt;int&gt; &lt;int&gt; &lt;int&gt;
##  1        2564      0     1     0
##  2        2564      1     1     0
##  3        2564      2     1     0
##  4        2564      3     1     0
##  5        2564      4     1     0
##  6        2564      5     1     0
##  7        2564      6     1     0
##  8        2564      7     1     0
##  9        2564      8     1     0
## 10        2564      9     1     0
## # ... with 14 more rows</code></pre>
</div>
</div>
<div id="humidity" class="section level3">
<h3><span class="header-section-number">4.6.3</span> Humidity</h3>
<p>What we can say at this point is that the temperatures in the city of Kiel have a clear seasonal pattern, but remain highly volatile intra-day and inter-day.</p>
<p>Weather however is not just defined as temperature, but humidity and precipitation play a role regarding our sensation and definition of weather as well.</p>
<p>Let’s have one look at humidity the same way we looked at temperatures as hourly averages:</p>
<p>Let’s plot the data again as hourly humidity averages per day:
<img src="lubridate_files/figure-html/ggplot%20avg%20RELATIVE_FEUCHTE-1.png" width="672" />
This plot shows the dryer months during the summer as having a lot more hours with lower humidity values than the months that fall into autumn and winter.</p>
</div>
</div>
<div id="wrap-up" class="section level2">
<h2><span class="header-section-number">4.7</span> Wrap up</h2>
<p>It was our objective to show and explain some of the more important features of the lubridate package. We can definitely say that handling this dataset in Base R would have been a lot more labourious. Lubridate has made working with this time series if not easy, but possible.
This statement goes for the other used packages in this exploration (dplyr, ggplot, etc.) without which the whole task would have been quite tedious.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="dplyr.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="forcats.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/tillschwoerer/R-data-science-book/blob/master/lubridate.Rmd",
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
